site_name: JP Mining on Steam Deck
site_url: https://aka-baka.github.io/deck-mining
site_description: Text extracting and Anki mining tips for Japanese games on the Steam Deck
site_author: aka_baka
nav:
  - Home:
    - Introduction: 'index.md'
  - Setup:
    - Setup Introduction: 'setupIntro.md'
    - Tools: 'setupTools.md'
    - Getting Things Ready Before Playing: 'beforePlaying.md'
    - Hooking Steam Games: 'hookSteamGames.md'
    - Hooking Lutris or Other proton Launcher Games: 'hookLutrisGames.md'
    - Hooking Linux Games or Emulators: 'hookEmuDeck.md'
    - Using OCR: 'OCR.md'
    - Mining to Anki: 'mining.md'
    - Controller Mapping: 'controller.md'
    - Demos: 'demos.md'
  - Extras:
    - Misc Tips: 'tips.md'
    - Resources: 'resources.md'
    - Run Windows: 'runWin.md'
  - Acknowledgements: 'acknowledgements.md'
    
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.annotation
    - content.code.copy
    - content.tabs.link
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: teal
      accent: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode    
      primary: teal
      accent: lime

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - git-revision-date-localized
  - search:
      lang:
        - en
        - ja
